import { Geist } from "next/font/google";
import Footer from "@/component/footer.jsx";
import Header from "@/component/headers.jsx";
import Whatsapp from "@/component/whatsapp.jsx";
import "./globals.css";

const geist = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
});

export const metadata = {
  title: "ParadiseFlower",
  description: "Generated by Ali Raza Yousaf",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={geist.className}>
        <Header />
        {children}
        <Whatsapp />
        <Footer />
      </body>
    </html>
  );
}
